version: '3'
services:
  puma-server:
    image: 486463126616.dkr.ecr.ap-northeast-1.amazonaws.com/match-app-image:puma-latest
    command: rails s -p 3000 -b '0.0.0.0' && rake db:migrate
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: match-app-service
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: match-app 
