version: '3'
services:
  puma-server:
    build: ./
    env_file: .docker-env
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    tty: true
    stdin_open: true
  postgres:
    image: postgres:10.5
    environment:
      IMPORT_FROM_DIR: /data
    ports:
      - 5432:5432
    volumes:
      - ./postgres/sh:/docker-entrypoint-initdb.d
      - ./postgres/data:/data
      - ./postgres/storage:/var/lib/postgresql/data